project:
  type: website

website:
  title: "langestroop.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/langestroop
      - icon: twitter
        href: https://twitter.com/langestroop
      - icon: scholar
        href: https://scholar.google.com/citations?user=93msY9YAAAAJ&hl=it&oi=ao 
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

