project:
  type: website

website:
  title: "Alberto Mariola"
  navbar:
    right:
      - text: Blog
      - href: blog.qmd
      - icon: github
        href: https://github.com/langestroop
      - icon: twitter
        href: https://twitter.com/langestroop
      - icon: scholar
        href: https://scholar.google.com/citations?user=93msY9YAAAAJ&hl=it&oi=ao 
format:
  html:
    theme: litera
    css: styles.css

editor: visual

