project:
  type: website
  output-dir: docs
website:
  title: "Alberto Mariola"
  navbar:
    right:
      - text: About
        href: about.md
      - text: Publications
        href: pubs.md
      - text: Blog
        href: blog.qmd
      #-text: Research
      # href: research.md
      - icon: github
        href: https://github.com/langestroop
      - icon: twitter
        href: https://twitter.com/langestroop
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=93msY9YAAAAJ&hl=it&oi=ao 
      
format:
  html:
    theme: litera
    css: styles.css

editor: visual

